package br.com.alura.conversor.model;

public enum CodigoMoeda {

    AED("Dirham dos Emirados Árabes Unidos"),
    AFN("Afegane"),
    ALL("Lek Albanês"),
    AMD("Dram Armênio"),
    ANG("Florim das Antilhas Holandesas"),
    AOA("Kwanza Angolano"),
    ARS("Peso Argentino"),
    AUD("Dólar Australiano"),
    AWG("Florim de Aruba"),
    AZN("Manat Azerbaijano"),
    BAM("Marco Conversível da Bósnia e Herzegovina"),
    BBD("Dólar de Barbados"),
    BDT("Taka de Bangladesh"),
    BGN("Lev Búlgaro"),
    BHD("Dinar do Bahrein"),
    BIF("Franco Burundiano"),
    BMD("Dólar das Bermudas"),
    BND("Dólar de Brunei"),
    BOB("Boliviano"),
    BRL("Real Brasileiro"),
    BSD("Dólar das Bahamas"),
    BTN("Ngultrum Butanês"),
    BWP("Pula de Botswana"),
    BYN("Rublo Bielorrusso"),
    BZD("Dólar de Belize"),
    CAD("Dólar Canadense"),
    CDF("Franco Congolês"),
    CHF("Franco Suíço"),
    CLP("Peso Chileno"),
    CNY("Renminbi Chinês"),
    COP("Peso Colombiano"),
    CRC("Colón Costa-Riquenho"),
    CUP("Peso Cubano"),
    CVE("Escudo de Cabo Verde"),
    CZK("Coroa Tcheca"),
    DJF("Franco do Djibuti"),
    DKK("Coroa Dinamarquesa"),
    DOP("Peso Dominicano"),
    DZD("Dinar Argelino"),
    EGP("Libra Egípcia"),
    ERN("Nakfa Eritreu"),
    ETB("Birr Etíope"),
    EUR("Euro"),
    FJD("Dólar de Fiji"),
    FKP("Libra das Ilhas Falkland"),
    FOK("Coroa Feroesa"),
    GBP("Libra Esterlina"),
    GEL("Lari Georgiano"),
    GGP("Libra de Guernsey"),
    GHS("Cedi Ganês"),
    GIP("Libra de Gibraltar"),
    GMD("Dalasi da Gâmbia"),
    GNF("Franco Guineano"),
    GTQ("Quetzal Guatemalteco"),
    GYD("Dólar da Guiana"),
    HKD("Dólar de Hong Kong"),
    HNL("Lempira Hondurenha"),
    HRK("Kuna Croata"),
    HTG("Gourde Haitiano"),
    HUF("Forint Húngaro"),
    IDR("Rupia Indonésia"),
    ILS("Novo Shekel Israelense"),
    IMP("Libra de Manx"),
    INR("Rupia Indiana"),
    IQD("Dinar Iraquiano"),
    IRR("Rial Iraniano"),
    ISK("Coroa Islandesa"),
    JEP("Libra de Jersey"),
    JMD("Dólar Jamaicano"),
    JOD("Dinar Jordaniano"),
    JPY("Iene Japonês"),
    KES("Xelim Queniano"),
    KGS("Som Quirguiz"),
    KHR("Riel Cambojano"),
    KID("Dólar do Kiribati"),
    KMF("Franco Comoriano"),
    KRW("Won Sul-Coreano"),
    KWD("Dinar Kuwaitiano"),
    KYD("Dólar das Ilhas Cayman"),
    KZT("Tenge Cazaque"),
    LAK("Kip Laosiano"),
    LBP("Libra Libanesa"),
    LKR("Rupia do Sri Lanka"),
    LRD("Dólar Liberiano"),
    LSL("Loti do Lesoto"),
    LYD("Dinar Líbio"),
    MAD("Dirham Marroquino"),
    MDL("Leu Moldávio"),
    MGA("Ariary Malgaxe"),
    MKD("Denar Macedônio"),
    MMK("Kyat de Mianmar"),
    MNT("Tugrik Mongol"),
    MOP("Pataca de Macau"),
    MRU("Ouguiya Mauritana"),
    MUR("Rupia Mauriciana"),
    MVR("Rufiyaa Maldiva"),
    MWK("Kwacha Malauiano"),
    MXN("Peso Mexicano"),
    MYR("Ringgit Malaio"),
    MZN("Metical Moçambicano"),
    NAD("Dólar da Namíbia"),
    NGN("Naira Nigeriana"),
    NIO("Córdoba Nicaraguense"),
    NOK("Coroa Norueguesa"),
    NPR("Rupia Nepalesa"),
    NZD("Dólar da Nova Zelândia"),
    OMR("Rial Omanense"),
    PAB("Balboa Panamenho"),
    PEN("Sol Peruano"),
    PGK("Kina da Papua Nova Guiné"),
    PHP("Peso Filipino"),
    PKR("Rupia Paquistanesa"),
    PLN("Złoty Polonês"),
    PYG("Guarani Paraguaio"),
    QAR("Rial Catarense"),
    RON("Leu Romeno"),
    RSD("Dinar Sérvio"),
    RUB("Rublo Russo"),
    RWF("Franco Ruandês"),
    SAR("Rial Saudita"),
    SBD("Dólar das Ilhas Salomão"),
    SCR("Rupia Seichelense"),
    SDG("Libra Sudanesa"),
    SEK("Coroa Sueca"),
    SGD("Dólar de Singapura"),
    SHP("Libra de Santa Helena"),
    SLL("Leone de Serra Leoa"),
    SOS("Xelim Somali"),
    SRD("Dólar do Suriname"),
    SSP("Libra Sul-Sudanesa"),
    STN("Dobra de São Tomé e Príncipe"),
    SYP("Libra Síria"),
    SZL("Lilangeni Suazi"),
    THB("Baht Tailandês"),
    TJS("Somoni Tadjique"),
    TMT("Manat Turcomeno"),
    TND("Dinar Tunisiano"),
    TOP("Paʻanga de Tonga"),
    TRY("Nova Lira Turca"),
    TTD("Dólar de Trinidad e Tobago"),
    TWD("Novo Dólar de Taiwan"),
    TZS("Xelim da Tanzânia"),
    UAH("Hryvnia Ucraniana"),
    UGX("Xelim de Uganda"),
    USD("Dólar Americano"),
    UYU("Peso Uruguaio"),
    UZS("Som Uzbeque"),
    VES("Bolívar Soberano Venezuelano"),
    VND("Dong Vietnamita"),
    VUV("Vatu de Vanuatu"),
    WST("Tala Samoano"),
    XAF("Franco CFA Central"),
    XCD("Dólar do Caribe Oriental"),
    XDR("Direitos Especiais de Saque"),
    XOF("Franco CFA Ocidental"),
    XPF("Franco CFP"),
    YER("Rial Iemenita"),
    ZAR("Rand Sul-Africano"),
    ZMW("Kwacha Zâmbiano"),
    ZWL("Dólar do Zimbábue");

    private final String nomeCompleto;
    CodigoMoeda(String nomeCompleto) {
        this.nomeCompleto = nomeCompleto;
    }

    public String getNomeCompleto() { return nomeCompleto; }

}